name: Test

on: [push]

jobs:
  Test:
    strategy:
      matrix:
        arch: [armv7, aarch64, s390x, ppc64le]
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run on exotic hardware
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: ${{matrix.arch}}
        distro: ubuntu_latest
        env: |
          CC: ${{matrix.cc}}
        install: |
          apt-get update -q -y
          apt-get install -q -y make
          apt-get install -q -y ${{matrix.cc}}
        run: cd test && make test
